language: swift
osx_image: xcode9.2

install:
  - gem install xcpretty

script:
  - xcodebuild -scheme ProjectTests -project ./Project.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty
